import { LinkedFileStorage } from '@_linked/core/utils/LinkedFileStorage';

/**
 * Where `/resized/*` keeps the derivatives it generates.
 *
 * A resize cache is not the same thing as user uploads, even though it has
 * always shared a folder with them. Uploads are the originals and must be kept;
 * derivatives are reproducible from those originals and can be dropped, rebuilt
 * or served from somewhere cheaper. Naming it separately lets an app make that
 * call rather than inheriting whatever the uploads store happens to be:
 *
 * ```ts
 * // keep originals in S3, but cache derivatives on the local disk
 * LinkedFileStorage.setStore(resizedImagesPurpose, new LocalFileStore('cache'));
 * ```
 *
 * Left alone it resolves to the default store, which is what the route did
 * before purposes existed — so nobody has to care unless they want to.
 *
 * The constant lives here rather than in core's `FileStorePurposes` because
 * core never writes a resized image; the package that owns the concept owns the
 * name.
 */
export const resizedImagesPurpose = 'resizedImages';

/**
 * The store for resized derivatives.
 *
 * The purpose is registered here, at the point of use, rather than as a side
 * effect of importing this module. The registry is process-global and can be
 * cleared while the process lives — `LinkedFileStorage.resetForTests()` does
 * exactly that — and an unregistered purpose makes `getStore` throw, which in a
 * request handler surfaces as a hung request rather than an error. Registering
 * on the way past is idempotent and removes the ordering rule entirely.
 */
export function getResizedImagesStore() {
  LinkedFileStorage.registerPurpose(resizedImagesPurpose, {
    description:
      'Resized image derivatives generated by GET /resized/*. Reproducible from the uploads store, so safe to clear.',
  });
  return LinkedFileStorage.getStore(resizedImagesPurpose);
}
