import { LinkedFileStorage } from '@_linked/core/utils/LinkedFileStorage';

/**
 * Where `/resized/*` keeps the derivatives it generates.
 *
 * A resize cache is not the same thing as user uploads, even though it has
 * always shared a folder with them. Uploads are the originals and must be kept;
 * derivatives are reproducible from those originals and can be dropped, rebuilt
 * or served from somewhere cheaper. Naming it separately lets an app make that
 * call rather than inheriting whatever the uploads store happens to be:
 *
 * ```ts
 * // keep originals in S3, but cache derivatives on the local disk
 * LinkedFileStorage.setStore(resizedImagesPurpose, new LocalFileStore('cache'));
 * ```
 *
 * Left alone it resolves to the default store, which is what the route did
 * before purposes existed — so nobody has to care unless they want to.
 *
 * The constant lives here rather than in core's `FileStorePurposes` because
 * core never writes a resized image; the package that owns the concept owns the
 * name. Registering it in the same module that exports it means importing the
 * constant is the registration, so ordering takes care of itself.
 */
export const resizedImagesPurpose = 'resizedImages';

const description =
  'Resized image derivatives generated by GET /resized/*. Reproducible from the uploads store, so safe to clear.';

LinkedFileStorage.registerPurpose(resizedImagesPurpose, { description });

/**
 * The store for resized derivatives, registering the purpose if it is missing.
 *
 * Registering again here rather than relying only on the import above, because
 * the registry is process-global state that can be cleared out from under this
 * module — `LinkedFileStorage.resetForTests()` does exactly that, and an
 * unregistered purpose makes `getStore` throw. Re-registering is idempotent
 * (an existing description is kept), so this is cheap insurance against an
 * ordering problem that would otherwise surface as a hung request.
 */
export function getResizedImagesStore() {
  LinkedFileStorage.registerPurpose(resizedImagesPurpose, { description });
  return LinkedFileStorage.getStore(resizedImagesPurpose);
}
